# Generated by Django 3.2.21 on 2023-11-11 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in', '0002_auto_20231107_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancetracking',
            name='error_flag',
        ),
    ]
