# Generated by Django 3.2.21 on 2023-11-11 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in', '0004_auto_20231111_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancetracking',
            name='location',
        ),
        migrations.RemoveField(
            model_name='attendancetracking',
            name='signout_date',
        ),
        migrations.RemoveField(
            model_name='attendancetracking',
            name='signout_time',
        ),
        migrations.AddField(
            model_name='attendancetracking',
            name='error_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancetracking',
            name='sign_out_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancetracking',
            name='sign_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendancetracking',
            name='signin_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendancetracking',
            name='signin_time',
            field=models.TimeField(),
        ),
    ]
