# Generated by Django 3.2.21 on 2023-11-15 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in', '0005_auto_20231111_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodservice',
            name='participant_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
