# Generated by Django 3.2.21 on 2023-11-15 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in', '0006_foodservice_participant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodservice',
            name='participant_name',
        ),
    ]
