# Generated by Django 3.2.21 on 2023-11-15 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in', '0007_remove_foodservice_participant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodservice',
            name='attendance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign_in.participant'),
        ),
    ]
